#!/bin/bash

# This script will run a monitoring check and print results in the /Monitoring directory.

# Using Colors for readability
RED='\033[0;31m'
LB='\033[1;34m'
CYAN='\033[1;36m'
NC='\033[0m'

sudo mkdir /Monitoring &> /dev/null
sudo touch /Monitoring/test &> /dev/null

echo -e -n "${CYAN}Hostname:${NC} " >> /Monitoring/test
sudo hostname >> /Monitoring/test

echo -e -n "${CYAN}LSB_Release:${NC} " >> /Monitoring/test
sudo lsb_release -s -d >> /Monitoring/test

echo -e "${CYAN}Current Kernel Information:${NC}" >> /Monitoring/test
sudo uname -o >> /Monitoring/test
sudo uname -r >> /Monitoring/test
sudo uname -m >> /Monitoring/test

load_val=$(cut -d " " -f 3 /proc/loadavg)
echo -e -n "${CYAN}Average Load (CPU/IO) Past 15min:${NC} " >> /Monitoring/test
sudo echo "${load_val}" >> /Monitoring/test

num_processes=$(ps aux --no-headers | wc -l)
echo -e -n "${CYAN}Number of Processes:${NC} " >> /Monitoring/test
sudo ps aux --no-headers | wc -l >> /Monitoring/test

echo -e -n "${CYAN}Uptime:${NC} " >> /Monitoring/test
sudo uptime -p >> /Monitoring/test

echo -e "${CYAN}Logged in Users:${NC}" >> /Monitoring/test
who >> /Monitoring/test

echo -e "${CYAN}Memory Usage in Mebibytes:${NC}" >> /Monitoring/test
free -m >> /Monitoring/test

echo -e "${CYAN}Disk Usage:${NC}" >> /Monitoring/test
df -H >> /Monitoring/test

echo -e "${CYAN}Running Containers:${NC}" >> /Monitoring/test
sudo lxc-ls -f --running >> /Monitoring/test

echo -e "${CYAN}Forever Processes:${NC}" >> /Monitoring/test
sudo forever list 2> /dev/null >> /Monitoring/test

echo -e "${CYAN}Top 5 Processes by CPU Usage:${NC}" >> /Monitoring/test
sudo ps aux --sort -%cpu | head -6 >> /Monitoring/test

echo -e "${CYAN}Top 5 Processes by Memory Usage:${NC}" >> /Monitoring/test
sudo ps aux --sort -%mem | head -6 >> /Monitoring/test

echo -e -n "${CYAN}Free Memory (Percent):${NC} " >> /Monitoring/test
sudo free | grep Mem | awk '{print $3/$2 * 100.0}' >> /Monitoring/test

echo -e -n "${CYAN}Memory In Use (Percent):${NC} " >> /Monitoring/test
sudo free | grep Mem | awk '{print $4/$2 * 100.0}' >> /Monitoring/test
