#!/bin/bash

# Data collection

d=$(date +%Y-%m-%d)
# This will go through yesterday's files
# d=$(date -d "1 day ago" +%Y-%m-%d)

total_collection_filepath=$(echo "/Data/cumulative")
total_collection_attackers_filepath=$(echo "/Data/cumulative_with_attackers")

for filename in /MITM/mitm_logs/$d/*.log; do
    echo $filename
    filepath=$(echo "/MITM/mitm_logs/$d/$filename")

    # Get time MITM started
    start_time=$(cat $filepath | grep "SSH man-in-the-middle server for" | cut -d " " -f 2)
    # If you don't want decimal points:
    # start_time=$(cat $filename | grep "SSH man-in-the-middle server for" | cut -d " " -f 2 | cut -d "." -f 1)

    # LXC Stream open and stream close (use as proxy for start and end of attacker session, other values like )
    LXC_stream_start=$(cat $filepath | grep "\[LXC Streams] New Stream" | cut -d " " -f 2)
    LXC_stream_end=$(cat $filepath | grep "\[LXC Streams] Removed Stream" | cut -d " " -f 2)
    time_in_system=$(($LXC_stream_end - $LXC_stream_start))
    # What happens when start and stop don't exist because no attacker?

    

    # Get level of system
    level=$(echo $filepath | cut -d "-" -f 3 | cut -d ":" -f 2 | cut -d "." -f 1)

    # First thing after line reader
    # cat $filename | grep "line from reader: " | cut -d " " -f 9

    # Count number of sudos
    sudo_count=$(grep -o 'sudo' "$filepath" | wc -l)

    # Count number of commands (ignoring empty lines)
    command_count=$(cat $filepath | grep "line from reader: " | cut -d " " -f 9 | grep "\S" | wc -l)



    # Here do we want to do # of wget and curl stuff to see how much malware commands




    echo "$LXC_stream_start $LXC_stream_end $time_in_system $level $sudo_count $command_count" >> $total_collection_filepath

    if [[ $time_in_system -ne "" ]]
    then
        echo "$LXC_stream_start $LXC_stream_end $time_in_system $level $sudo_count $command_count" >> $total_collection_attackers_filepath
    fi
done





# Random commands that we might want to keep a hold of:

# Get time attacker connected (last one if multiple connections made)
# attacker_connection_time=$(cat $filename | grep "\[Debug] \[Connection] Attacker connected:" | tail -1 | cut -d " " -f 2)

# Get time attacker broke auto access
# attacker_enter_system=$(cat $filename | grep "\[Debug] \[LXC-Auth] Attacker authenticated and is inside container" | cut -d " " -f 2)




