#!/bin/bash

#entire script requires a container name as an argument, along with an ip to listen to

#This part creates the container assuming a container with that name doesn't already exist, then starts it and assigns nat rules from host to container

if [ $# -ne 3 ]
then
  echo "Usage: Project_script <container_name>, <assigned_ip> <network_prefix> "
  exit 1
fi

container_name=$1
assigned_ip=$2
network_prefix=$3

sudo lxc-create -n $container_name -t download -- -d ubuntu -r focal -a amd64
sudo lxc-start -n $container_name
sleep 5

container_ip=$( sudo lxc-info -n $container_name | grep -w "IP:" | cut -d' ' -f14 )
sudo ip addr add $assigned_ip/$network_prefix brd + dev eth1

sudo iptables --table nat --insert PREROUTING --source 0.0.0.0/0 --destination $assigned_ip --jump DNAT --to-destination $container_ip
sudo iptables --table nat --insert POSTROUTING --source $container_ip --destination 0.0.0.0/0 --jump SNAT --to-source $assigned_ip

#The section below creates the MITM server
echo "Y" | sudo lxc-attach -n $container_name -- sudo apt install openssh-server

sudo sysctl -w net.ipv4.conf.all.route_localnet=1
sudo forever -l /home/student/MITM/logs/$container_name.log start /home/student/MITM/mitm.js -n $container_name -i $container_ip -p 1088 --auto-access --auto-access-fixed 3 --debug
sudo ip addr add $assigned_ip/16 brd + dev eth1
sudo iptables --table nat --insert PREROUTING --source 0.0.0.0/0 --destination $assigned_ip --jump DNAT --to-destination $container_ip
sudo iptables --table nat --insert POSTROUTING --source $container_ip --destination 0.0.0.0/0 --jump SNAT --to-source $assigned_ip
sudo iptables --table nat --insert PREROUTING --source 0.0.0.0/0 --destination $assigned_ip --protocol tcp --dport 22 --jump DNAT --to-destination 127.0.0.1:1088

  #The section below goes in tandem with the fake_wget and fake_curl scripts to poison the wget and curl commands and save links and downloads
echo "Y" | sudo lxc-attach -n $container_name -- bash -c "sudo apt-get upgrade wget"
echo "Y" | sudo lxc-attach -n $container_name -- bash -c "sudo apt-get upgrade curl"

sudo lxc-attach -n $container_name -- bash -c "mkdir /var/log/.downloads"
sudo lxc-attach -n $container_name -- bash -c "chmod a+w /var/log/.downloads"
sudo lxc-attach -n $container_name -- bash -c "cp /usr/bin/wget /usr/bin/fakewget"
cat /home/student/fake_wget | sudo tee /var/lib/lxc/$container_name/rootfs/usr/bin/wget > /dev/null 2>&1

sudo lxc-attach -n $container_name -- bash -c "cp /usr/bin/curl /usr/bin/fakecurl"
cat /home/student/fake_curl | sudo tee /var/lib/lxc/$container_name/rootfs/usr/bin/curl > /dev/null 2>&1