#!/bin/bash

# removes a container at the specified container name. The function will take in 2
if [ $# -ne 1 ]
then
    echo "Usage: container-delete <container name>"
    exit 1
fi

container_name=$1
container_number=$(echo $container_name | colrm 1 9)

# Stop the forever process
forever_id=$(sudo forever list | grep "$container_name" | tr -s ' '  | cut -d " " -f 17)
sudo forever stop $forever_id

# Might need to do this, not sure
# forever_pid=$(sudo forever list | grep "$container_name" | cut -d " " -f 20) | sudo kill -9 $forever_pid

# Removes the iptables rule blocking other attackers from entering the honeypot
iptables-save | grep -v "Drop other attackers $container_name" | iptables-restore

# Remove iptables rules
pub=$(echo "128.8.238.25 128.8.238.39 128.8.238.58 128.8.238.115 128.8.238.188" | cut -d " " -f $container_number)
ip_addr=$(sudo lxc-ls -f | grep "container$container_number" | tr -s " " | cut -d " " -f 5)
port=$((5000 + container_number))

# Stop and destroy the container
sudo lxc-stop -n "$container_name"
sudo lxc-destroy -n "$container_name"

# Removes nat rules
sudo iptables --table nat --delete PREROUTING --source 0.0.0.0/0 --destination $pub --jump DNAT --to-destination $ip_addr
sudo iptables --table nat --delete POSTROUTING --source $ip_addr --destination 0.0.0.0/0 --jump SNAT --to-source $pub
sudo iptables --table nat --delete PREROUTING --source 0.0.0.0/0 --destination $pub --protocol tcp --dport 22 --jump DNAT --to-destination 127.0.0.1:$port
