#!/bin/bash

# Container 1
filepath=$(cat /CurrentRunningFiles/container1)

most_recent_time=$(echo $filepath | cut -d "-" -f 3 | cut -d "/" -f 2)
curr_time_seconds=$(date '+%s')
recent_time_seconds=$(date -d "$most_recent_time" +%s)
difference=$(($curr_time_seconds - $recent_time_seconds))

if [ "$difference" -gt 1800 ]; then
    wall "failsafe activated for container1"
    sudo systemctl restart container1
fi


# Container 2
filepath=$(cat /CurrentRunningFiles/container2)

most_recent_time=$(echo $filepath | cut -d "-" -f 3 | cut -d "/" -f 2)
curr_time_seconds=$(date '+%s')
recent_time_seconds=$(date -d "$most_recent_time" +%s)
difference=$(($curr_time_seconds - $recent_time_seconds))

if [ "$difference" -gt 1800 ]; then
    wall "failsafe activated for container2 time: $difference"
    sudo systemctl restart container2
fi


# Container 3
filepath=$(cat /CurrentRunningFiles/container3)

most_recent_time=$(echo $filepath | cut -d "-" -f 3 | cut -d "/" -f 2)
curr_time_seconds=$(date '+%s')
recent_time_seconds=$(date -d "$most_recent_time" +%s)
difference=$(($curr_time_seconds - $recent_time_seconds))

if [ "$difference" -gt 1800 ]; then
    wall "failsafe activated for container3 time: $difference"
    sudo systemctl restart container3
fi


# Container 4
filepath=$(cat /CurrentRunningFiles/container4)

most_recent_time=$(echo $filepath | cut -d "-" -f 3 | cut -d "/" -f 2)
curr_time_seconds=$(date '+%s')
recent_time_seconds=$(date -d "$most_recent_time" +%s)
difference=$(($curr_time_seconds - $recent_time_seconds))

if [ "$difference" -gt 1800 ]; then
    wall "failsafe activated for container4 time: $difference"
    sudo systemctl restart container4
fi


# Container 5
filepath=$(cat /CurrentRunningFiles/container5)

most_recent_time=$(echo $filepath | cut -d "-" -f 3 | cut -d "/" -f 2)
curr_time_seconds=$(date '+%s')
recent_time_seconds=$(date -d "$most_recent_time" +%s)
difference=$(($curr_time_seconds - $recent_time_seconds))

if [ "$difference" -gt 1800 ]; then
    wall "failsafe activated for container5 time: $difference"
    sudo systemctl restart container5
fi