#!/bin/bash

process_new_line() {
    # local var=''
    while IFS= read -r path event file; do
        line1=$(tail -1 "$file")
        attacker_ip=$(echo "$line1" | cut -d ";" -f 2)
        # Need to add iptables rule
        if [ -n "$attacker_ip" ]; then
        echo $attacker_ip >> /LoginIPs
            sudo /sbin/iptables --insert INPUT --protocol tcp ! --source $attacker_ip --dport 5001 --jump DROP -m comment --comment "Drop other attackers container1"
        fi
        read
    done
}

inotifywait --monitor --event modify /MITM/logs/logins/container1.log | process_new_line