#!/bin/bash

# Accepts arguments of the container template name (1), public ip address (2), 
# mitm port (3), and container name (4). This script will create and start the
# container, get the ip address of the container, and install openssh on the
# container. Then it will set up the container as the corresponding system
# level. After, it will set up all of the routing rules and start the MITM
# server. 


container_variant=$1
assigned_ip=$2
mitm_port=$3
container_name=$4

sudo lxc-create -n $container_name -t download -- -d ubuntu -r focal -a amd64
sudo lxc-start -n $container_name

sleep 5

# pull ip address of container
container_ip=$(sudo lxc-ls -f | grep "$container_name " | tr -s " " | cut -d " " -f 5)

# Install openssh in the container.
echo "Y" | sudo lxc-attach -n $container_name -- sudo apt install openssh-server
# TODO: ###########################################################################
# Sets up container based on level indicated by randomly generated number. You will
# see this message when SSHing into the container. These parts will be replaced
# with scripts that will completely contruct the banners for our systems. These
# commands are here as placeholders for creating the systems to prove the randomness
# of our systems.
# TODO: #########################################################################
if [ $container_variant == 1 ]
then
    # level 1
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"This is a test message, beware! - Level 1\" > /etc/update-motd.d/00-header'
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"\" > /etc/update-motd.d/10-help-text'
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"\" > /etc/update-motd.d/50-motd-news'
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"\" > /etc/update-motd.d/91-contract-ua-esm-status'
    # Install all the things
    # Poison all the things
    # Change MOTD
elif [ $container_variant == 2 ]
then
    # level 2
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"Welcome to our secure system. Please adhere to all guidelines and use responsibly\" > /etc/update-motd.d/00-header'
elif [ $container_variant == 3 ]
then
    # level 3
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"Welcome\" > /etc/update-motd.d/00-header && \
    sudo echo printf \"By accessing this information system, you agree to comply with all applicable use policies and legal provisions.\n                                
                        Please be aware: \n                                                          
                        - This system is monitored every 24 hours to ensure proper functioning and to verify secure usage. \n                                                
                        - Your IP address and login times will be automatically recorded. \n          
                                                                           
                        In accordance with Maryland Criminal Law 7-302, unauthorized access, use, alteration, or damage to this \n
                        system may result in civil and/or criminal penalties with fines up to $10,000.\n    
                                                                                                                     
                        We value privacy and data protection. Use this system responsibly and always respect all applicable data protection laws. \n                            
                                                                              
                        If you do not agree to these terms, please LOG OFF IMMEDIATELY. \n\" >> /etc/update-motd.d/00-header'
elif [ $container_variant == 4 ]
then
    # level 4
    sudo lxc-attach -n $container_name -- bash -c 'sudo echo printf \"You are accessing a U.S. Government (USG) Information System (IS) that is  \n
                                                    provided for USG-authorized use only. By using this IS (which includes any \n
                                                    device attached to this IS), you consent to the following conditions: \n    
                                                                             
                                                \t - The United States Government may monitor, record, and audit your system usage, including \n
                                                usage of personal devices and email systems for official duties or to conduct business operations. \n
                                                Therefore, you have no reasonable expectation of privacy regarding any communication or data transiting \n
                                                or stored on this system. At any time, the government may for any lawful government purpose, monitor, intercept, \n
                                                search and seize any communication or data transiting or stored on this system. \n

                                                \t - Any communication or data transiting or stored on this system may be disclosed or used for any \n
                                                lawful government purpose. \n                    
                                                \t - Unauthorized or improper use of this system may result in disciplinary action, as well as \n
                                                civil and criminal penalties. \n
                                                You have been notified that the use of this system constitutes consent to monitoring and recording. \n                                              
                                                \t - Your IP address, login information, and data transactions will be logged and monitored \n
                                                continuously for cybersecurity and investigative purposes. \n

                                                Violation or unauthorized use of this system violates federal law under United States Code (U.S.C.), \n
                                                Title 18, Section 1030, which provides for fines up to $50,000 and imprisonment up to 20 years for \n
                                                unauthorized access or for exceeding authorized access to government computers. \n                                      
                                                                         
                                                By proceeding, you acknowledge your understanding and compliance with these warnings and consent to \n
                                                all of the above provisions.\" > /etc/update-motd.d/00-header'
fi

# Command needed for MITM server routing.
sudo sysctl -w net.ipv4.conf.all.route_localnet=1

# Get date and time variable for MITM file system.
d=$(date +%Y-%m-%d)
t=$(date +%T)

# Make the directories for the MITM file system.
sudo mkdir /MITM
sudo mkdir /MITM/mitm_logs
sudo mkdir /MITM/mitm_logs/$d

# Start the MITM server and make associated log file with time and name in the date directory.
# sudo forever -l /MITM/mitm_logs/$d/$t-$container_name-level:$container_variant.log start /MITM/mitm.js -n $container_name -i $container_ip -p $mitm_port --auto-access --auto-access-fixed 3 --debug
sudo forever -l /MITM/mitm_logs/$d/$t-$container_name-level:$container_variant.log start /MITM/mitm.js -n $container_name -i $container_ip -p $mitm_port --auto-access --auto-access-fixed 3

# Insert necessary nat rules.
sudo ip addr add $assigned_ip/16 brd + dev eth1
sudo iptables --table nat --insert PREROUTING --source 0.0.0.0/0 --destination $assigned_ip --jump DNAT --to-destination $container_ip
sudo iptables --table nat --insert POSTROUTING --source $container_ip --destination 0.0.0.0/0 --jump SNAT --to-source $assigned_ip
sudo iptables --table nat --insert PREROUTING --source 0.0.0.0/0 --destination $assigned_ip --protocol tcp --dport 22 --jump DNAT --to-destination 127.0.0.1:$mitm_port
