#!/bin/bash

# This script will stop and delete the 4 running containers in preparation
# for the creation of the new systems. It will also delete the previous
# nat routing rules.


# Stop all iptables rules that block to containers:
iptables-save | grep -v Drop other attackers container1 | iptables-restore
iptables-save | grep -v Drop other attackers container2 | iptables-restore
iptables-save | grep -v Drop other attackers container3 | iptables-restore
iptables-save | grep -v Drop other attackers container4 | iptables-restore





# Stop all forever (MITM) processes.
sudo forever stopall

# Stop container, delete container, and delete nat rules.
addrs=(128.8.238.25 128.8.238.39 128.8.238.58 128.8.238.115)
for i in 1 2 3 4
do
    ip_addr=$(sudo lxc-ls -f | grep "container$i" | tr -s " " | cut -d " " -f 5)
    pub=${addrs[$(($i - 1))]}
    port=$((5000 + $i))
    sudo lxc-stop -n "container$i"
    sudo lxc-destroy -n "container$i"
    sudo iptables --table nat --delete PREROUTING --source 0.0.0.0/0 --destination $pub --jump DNAT --to-destination $ip_addr
    sudo iptables --table nat --delete POSTROUTING --source $ip_addr --destination 0.0.0.0/0 --jump SNAT --to-source $pub
    sudo iptables --table nat --delete PREROUTING --source 0.0.0.0/0 --destination $pub --protocol tcp --dport 22 --jump DNAT --to-destination 127.0.0.1:$port
done
