#!/bin/bash

process_new_line() {
    # local var=''
    read
    while true
    do

        echo $REPLY | cut -d ";" -f 2 | sudo tee /LoginIPs3
        # Need to add iptables rule
        sudo iptables --insert INPUT --protocol tcp ! --source $attacker_ip --dport 5003 --jump DROP -m comment --comment "Drop other attackers container3"

        read
    done
}

touch /LoginIPs3
tail -n 0 -f /MITM/logs/logins/container3.log | process_new_line