#!/bin/bash

process_new_line() {
    # local var=''
    read
    while true
    do

        echo $REPLY | cut -d ";" -f 2 | sudo tee /Logouts
        # Need to remove iptables rule
        sudo iptables --insert INPUT --protocol tcp ! --source $attacker_ip --dport 5001 --jump DROP

        read
    done
}

touch /Logouts
tail -f /MITM/logs/logouts/container1.log | process_new_line