#!/bin/bash

process_new_line() {
    # local var=''
    read
    while true
    do

        echo $REPLY | cut -d ";" -f 2 | sudo tee /LoginIPs4
        # Need to add iptables rule

        read
    done
}

touch /LoginIPs4
tail -n 0 -f /MITM/logs/logins/container4.log | process_new_line