#!/bin/bash

process_new_line() {
    # local var=''
    read
    while true
    do

        echo $REPLY | cut -d ";" -f 2 | sudo tee /LoginIPs2
        # Need to add iptables rule

        read
    done
}

touch /LoginIPs2
tail -f /MITM/logs/logins/container2.log | process_new_line