#!/bin/bash

process_new_line() {
    # local var=''
    read
    while true
    do

        echo $REPLY | cut -d ";" -f 2 | sudo tee /Logouts
        # Need to remove iptables rule
        sudo iptables --delete INPUT --protocol tcp ! --source $attacker_ip --dport 5004 --jump DROP -m comment --comment "Drop other attackers container4"

        read
    done
}

touch /Logouts
tail -n 0 -f /MITM/logs/logouts/container4.log | process_new_line