#!/bin/bash

process_new_line() {
    # local var=''
    while IFS= read -r line
    do
        attacker_ip=$(echo "$line" | cut -d ";" -f 2)
        # Need to add iptables rule
        if [ -n "$attacker_ip" ]; then
        echo $attacker_ip >> /LoginIPs
            sudo /sbin/iptables --insert INPUT --protocol tcp ! --source $attacker_ip --dport 5002 --jump DROP -m comment --comment "Drop other attackers container2"
        fi
        read
    done
}

tail -n 0 -f /MITM/logs/logins/container2.log | process_new_line