#!/bin/bash

process_new_line() {
    # local var=''
    read
    while true
    do

        attacker_ip=$(echo $REPLY | cut -d ";" -f 2)
        # Need to add iptables rule
        sudo /sbin/iptables --insert INPUT --protocol tcp ! --source $attacker_ip --dport 5004 --jump DROP -m comment --comment "Drop other attackers container4"

        read
    done
}

tail -n 0 -f /MITM/logs/logins/container4.log | process_new_line
