#!/bin/bash
# container_name=$1

process_new_line() {
    # local var=''
    read
    while true
    do
        # ip_addr=$(echo $REPLY | cut -d ";" -f 2)
        # container_ip=$(sudo lxc-ls -f | grep "$container_name " | tr -s " " | cut -d " " -f 5)

        # Add an iptables rule to allow the ip address to (where?)
        # iptables --insert INPUT --source $ip_addr --destination $container_ip --jump DROP

        # Add an iptables rule to not allow all other connections to (where?)
        echo $REPLY | cut -d ";" -f 2 >> /Testfile

        read
    done
}

# tail -f /MITM/logs/logins/$container_name
touch /MITM/testfile
touch /Testfile
tail -f /MITM/testfile