#!/bin/bash

# Clone this repository or move it to the root directory (/).

# Loads all of the different firewall rules and packages that are required for future operations.

# Run default firewall rules provided to us.
sudo sh firewall_rules.sh
cd /

# Install forever for persistent node (MITM) processes.
sudo npm install -g forever

# Clone and install ACES MITM server.
# git clone https://github.com/fdeegbe/MITM.git
git clone https://github.com/UMD-ACES/MITM
cd ./MITM
sudo ./install.sh

# Ensure execute permissions are added on the recycle script.
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/recycle

# Execute permissions for data collection script.
chmod +x /1G-Ray-of-Light/DataCollection/collect_data


# Setup for data collection.
mkdir /Data
touch /Data/cumulative
touch /Data/cumulative_with_attackers
echo "Start_Time End_Time Time_In_System Level Sudo_Count Command_Count Malware_Count" | sudo tee Data/cumulative
echo "Start_Time End_Time Time_In_System Level Sudo_Count Command_Count Malware_Count" | sudo tee /Data/cumulative_with_attackers

# Set up crontab in root crontab for the permissions.
echo -e "*/10 * * * * /1G-Ray-of-Light/Recycling-LXC-Version/recycle\n*/5 * * * * /1G-Ray-of-Light/DataCollection/collect_data\n@reboot sh /1G-Ray-of-Light/Setup/firewall_rules.sh\n" | sudo crontab -



# # Set up crontab in root crontab for the permissions.
# echo -e "*/10 * * * * /1G-Ray-of-Light/Recycling-LXC-Version/recycle\n" | sudo crontab -

# # Set up crontab for data collection.
# echo -e "*/5 * * * * /1G-Ray-of-Light/DataCollection/collect_data\n" >> sudo crontab -

# # Set up firewall rules for reboot
# echo -e "@reboot sh /1G-Ray-of-Light/Setup/firewall_rules.sh\n" >> sudo crontab -