#!/bin/bash

# Clone this repository or move it to the root directory (/).

# Loads all of the different firewall rules and packages that are required for future operations.

# Run default firewall rules provided to us.
sudo sh firewall_rules.sh
cd /

# Install forever for persistent node (MITM) processes.
sudo npm install -g forever

# Clone and install ACES MITM server.
# git clone https://github.com/fdeegbe/MITM.git
git clone https://github.com/UMD-ACES/MITM
cd ./MITM
sudo ./install.sh

# Ensure execute permissions are added on the recycle script.
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/recycle

# Execute permissions for data collection script.
chmod +x /1G-Ray-of-Light/DataCollection/collect_data

# Permissions for following
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/taillogins1
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/taillogins2
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/taillogins3
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/taillogins4
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/taillogins5

chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/container-delete
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/recycle-delete
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/recycle-create

sudo cp /1G-Ray-of-Light/Setup/container1.service /lib/systemd/system/
sudo cp /1G-Ray-of-Light/Setup/container2.service /lib/systemd/system/
sudo cp /1G-Ray-of-Light/Setup/container3.service /lib/systemd/system/
sudo cp /1G-Ray-of-Light/Setup/container4.service /lib/systemd/system/
sudo cp /1G-Ray-of-Light/Setup/container5.service /lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable container1
sudo systemctl start container1
sudo systemctl enable container2
sudo systemctl start container2
sudo systemctl enable container3
sudo systemctl start container3
sudo systemctl enable container4
sudo systemctl start container4
sudo systemctl enable container5
sudo systemctl start container5

# Setup for data collection.
mkdir /Data
mkdir /Data/Failed
touch /Data/cumulative
touch /Data/cumulative_with_attackers

echo "Date Level Attacker_IP IsInteractive Command_Count Time_In_System Start_Time End_Time Banner_Count Sudo_Count Downloading_Count Compression_Count RW_Count Usersettings_Count Filename" | sudo tee /Data/cumulative_with_args


echo -e "0 1 * * * /1G-Ray-of-Light/DataCollection/collect_data\n@reboot sh /1G-Ray-of-Light/Setup/firewall_rules.sh\n\n" | sudo crontab -
