#!/bin/bash

# Clone this repository or move it to the root directory (/).

# Loads all of the different firewall rules and packages that are required for future operations.

# Run default firewall rules provided to us.
sudo sh firewall_rules.sh
cd /

# Install forever for persistent node (MITM) processes.
sudo npm install -g forever

# Clone and install ACES MITM server.
# git clone https://github.com/fdeegbe/MITM.git
git clone https://github.com/UMD-ACES/MITM
cd ./MITM
sudo ./install.sh

# Set up crontab in root crontab for the permissions.
echo -e "*/25 * * * * /1G-Ray-of-Light/Recycling-LXC-Version/recycle\n" | sudo crontab -

# Ensure execute permissions are added on the recycle script.
chmod +x /1G-Ray-of-Light/Recycling-LXC-Version/recycle

chmod +x /1G-Ray-of-Light/DataCollection/collect_data


# Setup for data collection.
sudo mkdir /Data
sudo touch /Data/cumulative
sudo touch /Data/cumulative_with_attackers