#!/bin/bash


# remove forever processes
# pid=$(sudo forever list | grep container1 | awk '{print $3}')
# sudo forever stop "$pid"

# pid=$(sudo forever list | grep container2 | awk '{print $3}')
# sudo forever stop "$pid"

# pid=$(sudo forever list | grep container3 | awk '{print $3}')
# sudo forever stop "$pid"

# pid=$(sudo forever list | grep container4 | awk '{print $3}')
# sudo forever stop "$pid"